# Generated by Django 2.1.5 on 2019-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_details', models.TextField()),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Onrequest', 'Onrequest')], default='Active', max_length=100)),
            ],
        ),
    ]
