# Generated by Django 2.1.5 on 2019-07-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='driver_profile',
        ),
    ]
